# Generated by Django 2.2.3 on 2019-07-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('reply_to_id', models.IntegerField()),
                ('reply_type', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Restraut',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('average_rate', models.CharField(max_length=100)),
                ('comment_num', models.IntegerField()),
                ('cate', models.ForeignKey(on_delete=None, to='bestsite.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('price', models.CharField(max_length=100)),
                ('man_num', models.IntegerField()),
                ('service_fee', models.CharField(max_length=100)),
                ('is_anoym', models.IntegerField()),
                ('rate', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('like_num', models.IntegerField()),
                ('dislike_num', models.IntegerField()),
                ('res', models.ForeignKey(on_delete=None, to='bestsite.Restraut')),
            ],
        ),
    ]
