# Generated by Django 2.2.3 on 2019-07-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestsite', '0002_reply_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='reply_to_uid',
            field=models.IntegerField(null=True),
        ),
    ]
